# Utilizando uma imagem base com suporte ao Java
FROM adoptopenjdk/openjdk17:alpine-jre
 
# Copiando o arquivo JAR Spring Boot para a imagem
COPY target/curriculo-0.0.1-SNAPSHOT.jar /app.jar
 
# Comando para executar a aplicação quando o container for iniciado
CMD ["java", "-jar", "/app.jar"]